name: Build Android

on:
  workflow_dispatch

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    - run: docker pull sumucheng/build-node:latest
    - name: Rename build-node image
      run: docker rename sumcheng/build-node:latest build-node
    # - name: Copy container output files to local
    #   run: docker cp container:/root/node/headers .
    #     |docker cp container:/root/node/out/Release/node .
    #     |docker cp container:/root/node/out/Release/libnode.so .
    #     |docker cp container:/system/lib/libc++_shared.so .
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: headers.zip
    #     path: ./headers
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: node
    #     path: ./node
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: libnode.so
    #     path: ./libnode.so
    # - uses: actions/upload-artifact@v3
      # with:
      #   name: libc++_shared.so
      #   path: ./libc++_shared.so
