name: Build Android

on:
  workflow_dispatch

jobs:
  build-arm64:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
