name: Build Android

on:
  workflow_dispatch

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull build-node docker image
      run: docker pull sumucheng/build-node
    - name: Run build-node image and set volume
      run: docker run --privileged --name container -v /home/runner/work/NodeForAndroid/NodeForAndroid/swap:/swap -d build-node /bin/build arm64
    - name: Wait for the container
      run: docker wait container
    
    # - name: Fetch headers
    #   run: export HEADERS_ONLY=1 && python3 ./tools/install.py install headers/
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: release.zip
    #     path: out/Release
