name: Build Android

on:
  workflow_dispatch

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Pull build-node docker image
      run: docker pull sumucheng/build-node
    # - name: Fetch headers
    #   run: export HEADERS_ONLY=1 && python3 ./tools/install.py install headers/
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: release.zip
    #     path: out/Release
