name: Build Platform

on:
  workflow_dispatch

jobs:
  build-arm64:
  
    runs-on: linux-x86_64
    
    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    - name: Pull build-node image
      run: docker pull sumucheng/build-node:latest
    - name: Create the container & Wait for the container
      run: docker run --privileged -v /home/runner/work/NodeForAndroid/NodeForAndroid/swap:/swap -t --name=container sumucheng/build-node:latest /bin/build aarch64
    - name: Copy output files to local
      run: docker cp container:/root/node/headers .
        |docker cp container:/root/node/out/Release/node .
        |docker cp container:/root/node/out/Release/libnode.so .
        |docker cp container:/system/lib/libc++_shared.so .
    - uses: actions/upload-artifact@v3
      with:
        name: headers_arm64.zip
        path: ./headers
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: node_arm64
        path: ./node
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: libnode_arm64.so
        path: ./libnode.so
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: libc++_shared_arm64.so
        path: ./libc++_shared.so
        if-no-files-found: error
        
  build-arm:
  
    runs-on: linux-x86_64
    
    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    - name: Pull build-node image
      run: docker pull sumucheng/build-node:latest
    - name: Create the container & Wait for the container
      run: docker run --privileged -v /home/runner/work/NodeForAndroid/NodeForAndroid/swap:/swap -t --name=container sumucheng/build-node:latest /bin/build arm
    - name: Copy output files to local
      run: docker cp container:/root/node/headers .
        |docker cp container:/root/node/out/Release/node .
        |docker cp container:/root/node/out/Release/libnode.so .
        |docker cp container:/system/lib/libc++_shared.so .
    - uses: actions/upload-artifact@v3
      with:
        name: headers_arm.zip
        path: ./headers
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: node_arm
        path: ./node
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: libnode_arm.so
        path: ./libnode.so
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: libc++_shared_arm.so
        path: ./libc++_shared.so
        if-no-files-found: error

  
  build-x86_64:
  
    runs-on: linux-x86_64
    
    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    - name: Pull build-node image
      run: docker pull sumucheng/build-node:latest
    - name: Create the container & Wait for the container
      run: docker run --privileged -v /home/runner/work/NodeForAndroid/NodeForAndroid/swap:/swap -t --name=container sumucheng/build-node:latest /bin/build x86_64
    - name: Copy output files to local
      run: docker cp container:/root/node/headers .
        |docker cp container:/root/node/out/Release/node .
        |docker cp container:/root/node/out/Release/libnode.so .
        |docker cp container:/system/lib/libc++_shared.so .
    - uses: actions/upload-artifact@v3
      with:
        name: headers_x86_64.zip
        path: ./headers
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: node_x86_64
        path: ./node
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: libnode_x86_64.so
        path: ./libnode.so
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: libc++_shared_x86_64.so
        path: ./libc++_shared.so
        if-no-files-found: error
  
  build-x86:
  
    runs-on: linux-x86_64
    
    steps:
    - uses: actions/checkout@v3
    - uses: docker-practice/actions-setup-docker@master
    - name: Pull build-node image
      run: docker pull sumucheng/build-node:latest
    - name: Create the container & Wait for the container
      run: docker run --privileged -v /home/runner/work/NodeForAndroid/NodeForAndroid/swap:/swap -t --name=container sumucheng/build-node:latest /bin/build x86
    - name: Copy output files to local
      run: docker cp container:/root/node/headers .
        |docker cp container:/root/node/out/Release/node .
        |docker cp container:/root/node/out/Release/libnode.so .
        |docker cp container:/system/lib/libc++_shared.so .
    - uses: actions/upload-artifact@v3
      with:
        name: headers_x86.zip
        path: ./headers
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: node_x86
        path: ./node
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: libnode_x86.so
        path: ./libnode.so
        if-no-files-found: error
    - uses: actions/upload-artifact@v3
      with:
        name: libc++_sharedx86.so
        path: ./libc++_shared.so
        if-no-files-found: error
